name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install SQLite
      run: sudo apt-get install -y libsqlite3-dev
    
    - name: Compile
      run: g++ src/*.cpp -Iinclude -o music_salon -lsqlite3
    
    - name: Done
      run: echo "Build OK"
